version: '3.8'

services:
  geosentinel:
    build: .
    container_name: geosentinel_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./geodata:/app/geodata
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tor-proxy:
    image: osminogin/tor-simple
    container_name: tor_service
    ports:
      - "8000:8000"
    restart: always